### ISSUE TITLE
Sales Rep - Move Data Fetch to Sub Panels

### ISSUE THREAD

**Issue by bitingmidge** [bezlio/bezlio-apps#114]
This is a bit of a larger design shift...

Right now the "Accounts View" panel performs the bulk of the data fetching from BRDB. Data is then passed to supporting bezls (Tasks, CRM Calls, etc...) via jQuery events and local storage. This causes issues keeping the in-memory data in sync between the various bezls.

Instead of having the "Accounts View" pull all of the data from BRDB, moving the responsibility for each bezl to fetch and maintain it's own data will alleviate some of that complexity. Ideally the only piece of data that will need to be passed via jQuery or local storage will be the selectedAccount.

**Comment by aellis** [comment]
Replaced by #366
