### ISSUE TITLE
Sales Rep - Accounts View - Incorrect URL formatting of web links

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#135]
The hyperlinks are being incorrectly formed to all prefix with portal.bezl.io.  There is a chance the link will work if the end URL automatically re-routes bad hostnames to www but it would not be consistent.  When you hover over the hyperlink it should only say the domain name of the site you will be visiting.

**Comment by kprice595** [comment]
Issue was fixed by pull request #156
