### ISSUE TITLE
Sales Rep - Accounts View - Established Data Display Inconsistency

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#157]
It has been reported that the established date field is inconsistently displaying.

**Comment by bitingmidge** [comment]
@aellis - In the standard Epicor10 GetAccounts.sql file the "Established Date" field is **Customer.EstDate**. For this particular customer it is **Customer_UD.EstablishedDate_c**. There are only four records that have any date filled in that field.

**Comment by aellis** [comment]
Thanks @bitingmidge, I am closing this one out.
