### ISSUE TITLE
Sales Rep - Accounts View - Sorts Not Preserved On Refresh

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#166]

**Comment by bitingmidge** [comment]
@aellis - I might need some more detail on this one. I'm not sure exactly what is being described by this issue.

**Comment by aellis** [comment]
@bitingmidge what I saw here was that I sorted by distance, clicked the refresh button, and then when the results came back the column seemed to indicate it was sorted by distance but the data definitely was not.

**Comment by bitingmidge** [comment]
@aellis Thank you. Should the sorting reset to default like the filtering does after clicking refresh? Or should the currently sorted column remain in effect?

**Comment by aellis** [comment]
I think ideally the existing sort would remain in effect but if that is difficult to accomplish I believe a sorting reset is fine as well.

**Comment by bitingmidge** [comment]
I was able to keep the existing sort and just submitted a pull request with the fix.
