### ISSUE TITLE
Sales Rep - Accounts View - Costmetic Tweaks

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#169]
In the drill-down view of accounts view, use some div tags to make the 'Other Info' and 'AR Aging' sections look more presentable in iOS devices.  The AR aging on iOS right now has all values below the labels despite there being plenty of room next to the labels.

**Comment by NDMO** [comment]
@aellis Do you have anything in particular you want done with 'other info'.  It is currently showing this for me: 
![image](https://cloud.githubusercontent.com/assets/20114911/25184786/6b1b756c-24e9-11e7-96a9-e9b5ac567a51.png)

**Comment by aellis** [comment]
@NDMO we might not have enough space to work with on Other Info to make it more presentable.  But the AR info definitely could use improvement.
