### ISSUE TITLE
Sales Rep - Map View - Add Driving Route Support

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#19]
Currently sales-rep.map-view simply shows a customer listing sorted by distance with pins placed on a Google map to various customers near the user.  Feature request here is to add a 'Selected' checkbox within the customers grid and a new button along the bottom that will allow the user to generate a multi-destination route in Google maps.  This should be doable simply with a URL call with multi-address query parameters to Google maps.  I've seen documentation of this working on the desktop, what I don't know with certainty is whether it works the same on an iPhone so we will need to test that approach and fall back onto the option of doing it with the Google Maps API.

**Comment by OnlyAGhost** [comment]
This ended up becoming trip planner instead of map view. Not sure if we keep map view, I left it in there and added a new code base for trip planner.
