### ISSUE TITLE
Closed accounts displaying in CRM Mobile for MWhite

### ISSUE THREAD

**Issue by ITAppsTeam** [bezlio/bezlio-apps#214]
Accounts GARPLUS and ENVCON are closed and displaying in Michelle's view.  The Customer.Date02 field is populated for some closed accounts. This is a custom closed date field in Customer.  Please add this to the criteria for closed accounts.

Thank you,
Debra

**Comment by aellis** [comment]
All queries have been updated to ensure that Date02 is null.  This looks to have correctly pulled the noted accounts from the results.
