### ISSUE TITLE
Sales Rep - Order Inquiry / Invoice Inquiry / Price List / RMA Inquiry - Add Customer Selector

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#255]
Currently even though the above listed are "stand-alone apps" they rely on the account-view to pick the customer.  Enhance the noted apps per the following:

1. Where we currently have the selected account, replace this with a drop-down of all available accounts where the selected account is defaulted.
2. Add to this drop-down a first value of 'All Accounts' and set this to the default if now account was selected from accounts-view.
3. Revise the queries to accept this input in addition to the new 'All Accounts' option.

**Comment by j120foredeck** [comment]
Note that the current OrderInquiry.sql script does not include the current user email filter parameter, instead relying on the GetAccounts.sql filtered list.  When the Order Inquiry view is set to "All Accounts", the list of orders needs to be limited to those for the current sales rep.  Please add that parameter to ensure the reps only see the orders that apply to them.
