### ISSUE TITLE
Sales Rep - Tasks View - Push Updated Due Date

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#27]
On sales-rep.accounts-view we have a column for 'Next Task Due' that is filled when the initial query runs.  If a task is added in sales-rep.tasks-view we are not automatically updating this value.  I believe we will need a jQuery emitter / subscriber to push the change from task -> accounts, but try first to just update bezl.vars.selectedAccount to see if it happens automatically.

**Comment by aellis** [comment]
@bitingmidge - I did not seem to see this behavior operate as expected which leads me to believe we may have had an overwrite somewhere along the line of this feature addition.  Can you look into getting it re-established?

**Comment by bitingmidge** [comment]
After further testing this appears to be working correctly. Issues were probably due to some incompatible JS file versions being used in the bezls where the regression was observed.
