### ISSUE TITLE
Advanced Grid - selectRow Function - Cannot read property 'sequence'

### ISSUE THREAD

**Issue by KCraneGH** [bezlio/bezlio-apps#307]
The following adjustments were made to correct when selecting the last row:

![image](https://user-images.githubusercontent.com/25905345/28170375-3bc9ea34-67b3-11e7-814b-8e451e13a1bf.png)

**Comment by aellis** [comment]
Thanks for the fix on this one Keith.  This just committed to dev and will be part of our release over this weekend.
