### ISSUE TITLE
Sales Rep - Accounts View - Add AR Aging In Details

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#45]
In the details view, add a new panel for 'AR Aging' with the following fields:

Current
30-60
60-90
120+

Matt H will assist in the development in the query modifications required to add these columns.

**Comment by aellis** [comment]
@kprice595 has some capacity, so assigning this one to him unless @bitingmidge is in progress.

**Comment by bitingmidge** [comment]
@aellis @kprice595 - Nope, not in progress yet... go ahead
