### ISSUE TITLE
Sales Rep - Accounts View - Add Hours of Operation, Customer Website, and Social Media Links

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#46]
On the accounts view add the following fields on the drill-down view:

Other Info:
- Hours of Operation
- Website (with click to navigate)

Contacts:
- Twitter
- LinkedIn
- Facebook

Only show these values if they are present, much like we do for things like the contact title.  Matt H will assist with the revisions required to add this to the query.

**Comment by aellis** [comment]
In addition to the previously noted:

Other Info:
- Ship Via
- Freight Terms

Contacts:
- An indicator that the given contact is the appropriate contact for new order confirmations.

Notes: (new panel, full width):
- Note Type
- Note Details

Notes will act as a bit of a catch-all for fields to display that don't fit within any of our other standard fields.  You may need a separate query for these as it will be a multi-result thing.  Some initial notes requested by a customer by a customer include (as examples):

- Customer Level (custom field they utilize)
- General Notes

**Comment by aellis** [comment]
@kprice595 has some capacity, so assigning this one to him unless @bitingmidge is in progress.

**Comment by bitingmidge** [comment]
@aellis @kprice595 - Nope, not in progress yet... go ahead

**Comment by aellis** [comment]
@kprice595 Ship Via and Freight Terms appear to be missing from the markup.  Please re-add.
