### ISSUE TITLE
Common - Crystal Reports Viewer - UI Improvements

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#51]
- Remove the zebra striping on the report listing.
- Add a refresh button to the report listing.
- Hide the 'Update Parameters' button when there are no parameters to update.

**Comment by aellis** [comment]
@aellis is taking this one back.

**Comment by bitingmidge** [comment]
Seemed to be some JSON issue with the merge. Reverted with pull request #199

**Comment by bitingmidge** [comment]
Attempting merge again with pull request #202

**Comment by bitingmidge** [comment]
Reopening because can't merge pull request because throwing error due to bezlio/bezlio#358
