### ISSUE TITLE
Sales Rep - Task View - Multi-New Row Support

### ISSUE THREAD

**Issue by aellis** [bezlio/bezlio-apps#55]
The Epicor BO for Task.UpdateExt does not support pushing multiple *new* rows at once (updates are fine).  Update the Epicor library for CRM to detect when multiple new rows are present and, when detected, fire off multiple UpdateExt calls as opposed to just a single.

**Comment by bitingmidge** [comment]
![img_2551](https://cloud.githubusercontent.com/assets/24413547/23864005/a0f238fc-07e7-11e7-9fdc-ba4c57d48c27.PNG)
