### ISSUE TITLE
Sales Rep - Task View - Character Limitation for Description Field

### ISSUE THREAD

**Issue by bitingmidge** [bezlio/bezlio-apps#76]
When adding a task with too many characters in the description the save will fail with an error of: "The maximum number of characters allowed for Description is 30."

![image](https://cloud.githubusercontent.com/assets/24413547/23904338/e31b7d7c-089d-11e7-95bb-0fbd68ea8998.png)

@aellis: I'm assuming this character limitation is ultimately set by the backend plugin (in this case Epicor)?

**Comment by aellis** [comment]
@bitingmidge, that is true.  Epicor seems to impose a 30 character limit but this could vary by system we integrate with.
